apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-app-ingress
  namespace: app
spec:
  rules:
    - host: app-krishna.com   
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-app-service  
                port:
                  number: 80               

